### ISSUE TITLE
RPC endpoint reports ChainID:25

### ISSUE THREAD

**Issue by 0xHiro-Protagonist** [LATOKEN/lachain#234]
Per [Github's Chainlist](https://github.com/ethereum-lists/chains/commit/18b592ec7e23f9d4c97f613471153382a697df53) it should be ChainID:225.

This will cause issues with a number of providers. Error shown when trying to add via MetaMask:
![Error](https://user-images.githubusercontent.com/105400120/167970610-060ade60-930c-4bad-b639-36fa48c84aa1.png)

**Comment by sgladkov** [comment]
Sorry,  missed your message. We were in process of network transfer to the new chainId (from 25 to 225). Now it is completed,  225 is returned,  you can check it.
